# Github Action Job to refresh my personal spotify account's weekly playlist

name: Discover Weekly Action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2' # Every Tuesday at 0 UTC

jobs:

  Discover_Weekly_Job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Discover Weekly script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }},
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }},
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }},
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }},
        USERNAME: ${{ secrets.USERNAME }},
        DISCOVER_WEEKLY_ID: ${{ secrets.DISCOVER_WEEKLY_ID }},
        ALL_DISCOVERED_PLAYLIST_ID: ${{ secrets.ALL_DISCOVERED_PLAYLIST_ID }}
      run: |
        python discoverWeekly.py

