# Github Action Job to refresh my personal spotify account's weekly playlist

name: Python application

on:
  workflow_dispatch:

jobs:
  Discover_Weekly_Job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Echo GHA url 
      run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      shell: bash
    - name: Run the Discover Weekly python script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: python discoverWeekly.py
  
